### ISSUE TITLE
elements names can't be used for mixins names  

### ISSUE THREAD

**Issue by rabio** [less/old-lesscss.org#4]
[Documentation](http://lesscss.org/#-mixins) on the lesscss.org site states:

> Any CSS class, id or element ruleset can be mixed-in that way.

but unfortunately this isn't true for elements.

For example code below produces error on compilation:

``` css
div {
    display: table;
}

.some-class {
    div;
}
```
