### ISSUE TITLE
Missing `{` in example

### ISSUE THREAD

**Issue by cloudhead** [less/old-lesscss.org#68]
In the variable scope/redefinition section, a `{` is missing:

``` css
@var: 0;
.class1         /* here */
  @var: 1;
  .class {
    @var: 2;
    three: @var;
    @var: 3;
  }
  one: @var;
}

```
